### ISSUE TITLE
Extract Contributing Example Prooph Board

### ISSUE THREAD

**Issue by bofalke** [proophboard/cody-engine#42]
To have a playground for the cody code generation it would help to have the prooph board that would create the contribution mode setup for local development. 

[Example Board for Development](https://app.prooph-board.com/inspectio/board/b13afec8-cb3c-4e4a-b587-9db945a6db3d)

**Comment by codeliner** [comment]
You can find the example [here](https://app.prooph-board.com/inspectio/board/b13afec8-cb3c-4e4a-b587-9db945a6db3d?cells=9FRGHaQYGddKNuR7s3DaPq&clicks=1)

Unfortunately, I changed the board after generating the contribution example to try out some more Cody features. So I had to revert some metadata changes to align it again with the contribution example. It should be in sync now, but maybe I forgot something so keep an eye on it while running the first tests against the example.
